"use client"
import {useState,useRef,useEffect} from "react"
export default function Home(){
const [tab,setTab]=useState("feed")
const [myHostel,setMyHostel]=useState("W4 Annex")
const [joined,setJoined]=useState(["W4 Annex"])
const [members,setMembers]=useState({"W4 Annex":243,"NDDC Male":312,"NDDC Female":298,"W2A":180,"W5":210,"Town Campus":165,"NEEDS":120,"New NDDC":200,"Medical Hostel":150,"Haldeen":190,"OFF CAMPUS":400})
const [notifs,setNotifs]=useState([{id:1,text:"Favour mentioned you @You",time:"2m",read:false,type:"mention"},{id:2,text:"John liked your comment",time:"5m",read:false,type:"like"},{id:3,text:"New message from Campus Buka",time:"now",read:false,type:"message"}])
const [popup,setPopup]=useState(null)
const [unread,setUnread]=useState(3)
const [statusList,setStatusList]=useState([
{name:"You",ava:"🧑",items:[{id:1,txt:"In W4 Annex reading GST 😭",time:"10m",likes:12,views:45,liked:false}]},
{name:"Favour E.",ava:"👩",items:[{id:2,txt:"My hostel view!",time:"30m",likes:23,views:89,liked:true},{id:3,txt:"Second status today!",time:"1h",likes:5,views:20,liked:false}]},
{name:"Campus Buka",ava:"🍛",items:[{id:4,txt:"Jollof ready! ₦1500",time:"1h",likes:56,views:120,liked:false}]}
])
const [activeStatus,setActiveStatus]=useState(null)
const [sIdx,setSIdx]=useState(0)
const [newStatus,setNewStatus]=useState("")
const [showStatus,setShowStatus]=useState(false)
const [commentFor,setCommentFor]=useState(null)
const [commentTxt,setCommentTxt]=useState("")
const [editId,setEditId]=useState(null)
const [replyFor,setReplyFor]=useState(null)
const [shareFor,setShareFor]=useState(null)
const [showReact,setShowReact]=useState(null)
const [rec,setRec]=useState(false)
const [recFor,setRecFor]=useState(null)
const mrRef=useRef(null)
const [price,setPrice]=useState("all")
const reacts=["❤️","👍","😂","😭","😍","🔥","🙏","💀","🎉","👏","😎","🥺","🤣","❤️‍🔥","💯","😡","😮","🥰","🤩","😴","🤔","😏","🫡","👌","🫶","✨","💔","😇","🤯","🥲"]
const hostels=["NDDC Male","NDDC Female","W2A","W5","W4 Annex","Town Campus","NEEDS","New NDDC","Medical Hostel","Haldeen","OFF CAMPUS"]
const playTone=(t)=>{try{const c=new (window.AudioContext||window.webkitAudioContext)();const o=c.createOscillator();const g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=t==="mention"?880:t==="message"?650:500;g.gain.value=0.35;o.start();g.gain.exponentialRampToValueAtTime(0.01,c.currentTime+0.6);o.stop(c.currentTime+0.6)}catch(e){}if("vibrate" in navigator)navigator.vibrate(200)}
const push=(txt,type)=>{setNotifs(p=>[{id:Date.now(),text:txt,time:"now",read:false,type},...p]);setPopup({text:txt,type});playTone(type);setTimeout(()=>setPopup(null),3000);if("Notification" in window&&Notification.permission==="granted"){new Notification("Uniuyo Connect 🔊",{body:txt})}}
useEffect(()=>{if("Notification" in window&&Notification.permission!=="granted")Notification.requestPermission()},[])
const [posts,setPosts]=useState([
{id:1,name:"Favour E.",tag:"19/AG/BCH/123 • Agriculture",time:"2h",text:"Who has GST 111 past questions? 😭",react:"❤️",rc:13,liked:true,comments:[{id:101,name:"You",text:"I get am, DM me",react:"👍",rc:2,liked:false},{id:102,name:"John",text:"Same here",react:"😂",rc:1,liked:false}]},
{id:2,name:"Campus Buka",tag:"Vendor • Food Review",time:"5h",text:"Jollof + Chicken ₦1500 today! Free delivery NDDC - Who don chop?",react:"❤️",rc:46,liked:true,comments:[]}
])
const [market,setMarket]=useState([{id:1,name:"Jollof + Chicken",price:1500,pt:"₦1500",seller:"Campus Buka",img:"🍛",hostel:"NDDC Male",sold:false},{id:2,name:"Power Bank 20k mAh",price:8000,pt:"₦8000",seller:"You",img:"🔋",hostel:"W4 Annex",sold:false}])
const [msgs,setMsgs]=useState([{id:1,from:"seller",text:"Jollof still available?",type:"text"},{id:2,from:"you",text:"Yes boss",type:"text"}])
const [chatInput,setChatInput]=useState("")
const [txt,setTxt]=useState("")
const delComment=(pId,cId)=>{if(confirm("Delete?")){setPosts(posts.map(p=>p.id!==pId?p:{...p,comments:p.comments.filter(c=>c.id!==cId)}));push("Comment deleted 🗑️","like")}}
const startEdit=(c)=>{setEditId(c.id);setCommentTxt(c.text)}
const reactPost=(id,e)=>{setPosts(posts.map(p=>p.id===id?{...p,react:e,rc:p.react===e?p.rc:p.rc+1,liked:true}:p));setShowReact(null);push(`Reacted ${e}`,"like");playTone("like")}
const toggleHostel=(h)=>{if(joined.includes(h)){setJoined(joined.filter(x=>x!==h));setMembers({...members,[h]:members[h]-1});push(`Left ${h} 👋`,"like")}else{setJoined([...joined,h]);setMembers({...members,[h]:(members[h]||0)+1});push(`Joined ${h} 🎉 🔊`,"mention");playTone("mention")}}
const addStatus=()=>{if(!newStatus.trim())return;const item={id:Date.now(),txt:newStatus,time:"now",likes:0,views:1,liked:false};setStatusList(s=>{const me=s.find(x=>x.name==="You");if(me)return s.map(x=>x.name==="You"?{...x,items:[item,...x.items]}:x);else return[{name:"You",ava:"🧑",items:[item]},...s]});setNewStatus("");setShowStatus(false);push("Status added! 🔊","mention")}
const likeStatus=(uI,iI)=>{setStatusList(s=>s.map((u,ui)=>ui!==uI?u:{...u,items:u.items.map((it,ii)=>ii!==iI?it:{...it,likes:it.liked?it.likes-1:it.likes+1,liked:!it.liked})})));playTone("like")}
const shareTo=(uI,iI,target)=>{const it=statusList[uI].items[iI];if(target==="timeline"){setPosts([{id:Date.now(),name:"You",tag:`Shared status • ${myHostel}`,time:"now",text:it.txt,react:"❤️",rc:0,liked:false,comments:[]},...posts]);push("Status to Timeline ↗️","mention")}else if(target==="whatsapp"){const m=`${it.txt} - View on Uniuyo Connect (register to view): https://t-wine.vercel.app/?register=1`;window.open(`https://wa.me/?text=${encodeURIComponent(m)}`,"_blank")}else push(`Shared to ${target} 🏠`,"mention")}
const viewStatus=(i)=>{setActiveStatus(i);setSIdx(0);setStatusList(s=>s.map((u,idx)=>idx!==i?u:{...u,items:u.items.map(it=>({...it,views:it.views+1}))}))}
const startRec=(forWhere)=>{setRec(true);setRecFor(forWhere);playTone("message");navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{const mr=new MediaRecorder(stream);mrRef.current=mr;const ch=[];mr.ondataavailable=e=>ch.push(e.data);mr.onstop=()=>{const blob=new Blob(ch,{type:"audio/webm"});const url=URL.createObjectURL(blob);if(forWhere==="chat"){setMsgs([...msgs,{id:Date.now(),from:"you",text:"🎤 Voice",type:"voice",url}]);push("Voice note sent 🎤","message")}else{setPosts(posts.map(p=>p.id!==commentFor?p:{...p,comments:[...p.comments,{id:Date.now(),name:"You",text:"🎤 Voice (1min max)",react:"🎤",rc:0,liked:false,voice:url}]}))}setRec(false)};mr.start();setTimeout(()=>{if(mr.state==="recording")mr.stop()},forWhere==="comment"?60000:300000)}).catch(()=>{alert("Mic needed");setRec(false)})}
const shareWA=(t,isC)=>{const l="https://t-wine.vercel.app/?ref=whatsapp&register=1";const m=`${t}\n\n👀 View full ${isC?"comment":"post"} on Uniuyo Connect (register to view):\n${l}`;window.open(`https://wa.me/?text=${encodeURIComponent(m)}`,"_blank");push("Shared to WhatsApp 🔐","mention")}
const filtered=market.filter(m=>{if(price==="low")return m.price<2000;if(price==="mid")return m.price>=2000&&m.price<=10000;if(price==="high")return m.price>10000;return true})

return(
<div style={{minHeight:"100vh",background:"#f5f5f5",paddingBottom:90}}>
{popup&&<div style={{position:"fixed",top:65,left:10,right:10,background:"#0f172a",color:"white",padding:14,borderRadius:14,zIndex:999,display:"flex",justifyContent:"space-between"}}><div><b>🔔 {popup.type==="message"?"New Message 🔊":"Notification 🔊"} *DING*</b><div style={{fontSize:11}}>{popup.text}</div></div><span>🔊</span></div>}
<div style={{background:"white",padding:"12px 16px",borderBottom:"1px solid #eee",display:"flex",justifyContent:"space-between",position:"sticky",top:0,zIndex:20}}><b>🎓 Uniuyo Connect</b><div style={{display:"flex",gap:10}}><span onClick={()=>setTab("status")} style={{fontSize:18}}>📸</span><span onClick={()=>setTab("chat")} style={{position:"relative",fontSize:18}}>💬{unread>0&&<span style={{position:"absolute",top:-8,right:-10,background:"red",color:"white",fontSize:9,padding:"2px 6px",borderRadius:10}}>{unread}</span>}</span><span onClick={()=>setTab("notifs")} style={{position:"relative",fontSize:18}}>🔔{notifs.filter(n=>!n.read).length>0&&<span style={{position:"absolute",top:-8,right:-8,background:"red",color:"white",fontSize:9,padding:"2px 5px",borderRadius:10}}>{notifs.filter(n=>!n.read).length}</span>}</span></div></div>

{tab==="feed"&&<div style={{background:"white",padding:"10px 12px",display:"flex",gap:12,overflowX:"auto",borderBottom:"1px solid #f3f4f6"}}>{statusList.map((s,i)=><div key={i} onClick={()=>viewStatus(i)} style={{minWidth:62,textAlign:"center"}}><div style={{width:54,height:54,borderRadius:27,border:s.name==="You"?"2px dashed #2563eb":"3px solid #10b981",background:"#f3f4f6",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22}}>{s.ava}</div><div style={{fontSize:10,fontWeight:"bold"}}>{s.name}</div><div style={{fontSize:9,color:"#6b7280"}}>{s.items.length} status • {s.items[0]?.views} views</div></div>)}<div onClick={()=>setShowStatus(true)} style={{minWidth:62,textAlign:"center"}}><div style={{width:54,height:54,borderRadius:27,background:"#e5e7eb",display:"flex",alignItems:"center",justifyContent:"center",fontSize:22}}>+</div><div style={{fontSize:10}}>Add Status</div></div></div>}

{showStatus&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.8)",zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div style={{background:"white",padding:20,borderRadius:16,width:"100%",maxWidth:320}}><h3>Add Status</h3><textarea value={newStatus} onChange={e=>setNewStatus(e.target.value)} placeholder="What you dey do? Others can like, comment, share, see views" style={{width:"100%",padding:12,borderRadius:12,border:"1px solid #eee",marginTop:10}} rows={3}/><div style={{display:"flex",gap:8,marginTop:10}}><button onClick={()=>setShowStatus(false)} style={{flex:1,padding:10,borderRadius:10,border:"1px solid #eee",background:"white"}}>Cancel</button><button onClick={addStatus} style={{flex:1,padding:10,borderRadius:10,border:"none",background:"#2563eb",color:"white",fontWeight:"bold"}}>Post Status 🔊</button></div><div style={{fontSize:10,color:"#6b7280",marginTop:8}}>Add as many as you want • Others see who viewed/liked/commented/shared</div></div></div>}

{activeStatus!==null&&<div style={{position:"fixed",inset:0,background:"black",zIndex:200,color:"white",display:"flex",flexDirection:"column"}}><div style={{padding:12,display:"flex",justifyContent:"space-between"}}><span onClick={()=>setActiveStatus(null)}>✕ Close</span><span style={{fontSize:12}}>{sIdx+1}/{statusList[activeStatus]?.items.length} • {statusList[activeStatus]?.items[sIdx]?.views} 👁️ views</span></div><div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",padding:20,textAlign:"center"}}><div style={{fontSize:22}}>{statusList[activeStatus]?.items[sIdx]?.txt}</div></div><div style={{padding:12,background:"rgba(255,255,255,0.1)"}}><div style={{display:"flex",justifyContent:"space-around",marginBottom:12}}><span onClick={()=>likeStatus(activeStatus,sIdx)}>{statusList[activeStatus]?.items[sIdx]?.liked?"❤️":"🤍"} {statusList[activeStatus]?.items[sIdx]?.likes} Like</span><span>💬 Reply</span><span>👁️ {statusList[activeStatus]?.items[sIdx]?.views} Likes/Comments/Shares</span></div><div style={{display:"flex",gap:6,overflowX:"auto"}}><button onClick={()=>shareTo(activeStatus,sIdx,"timeline")} style={{padding:"8px 12px",borderRadius:20,background:"#2563eb",color:"white",border:"none",fontSize:11}}>↗️ Timeline</button><button onClick={()=>shareTo(activeStatus,sIdx,"whatsapp")} style={{padding:"8px 12px",borderRadius:20,background:"#25D366",color:"white",border:"none",fontSize:11}}>💬 WhatsApp + Register Gate</button>{hostels.slice(0,2).map(h=><button key={h} onClick={()=>shareTo(activeStatus,sIdx,h)} style={{padding:"8px 12px",borderRadius:20,background:"white",color:"black",border:"none",fontSize:11}}>🏠 {h}</button>)}</div></div><div style={{display:"flex",gap:4,padding:8}}>{statusList[activeStatus]?.items.map((_,ii)=><div key={ii} onClick={()=>setSIdx(ii)} style={{flex:1,height:3,background:ii===sIdx?"white":"rgba(255,255,255,0.3)",borderRadius:2}}></div>)}</div></div>}

{tab==="feed"&&<div style={{padding:12}}><div style={{background:"white",padding:12,borderRadius:16,marginBottom:12}}><textarea value={txt} onChange={e=>setTxt(e.target.value)} placeholder={`What's happening in ${myHostel}?`} style={{width:"100%",background:"#f3f4f6",border:"none",padding:12,borderRadius:12,outline:"none"}} rows={2}/><button onClick={()=>{if(txt.trim()){setPosts([{id:Date.now(),name:"You",tag:myHostel,time:"now",text:txt,react:"❤️",rc:0,liked:false,comments:[]},...posts]);setTxt("")}}} style={{marginTop:8,width:"100%",background:"#2563eb",color:"white",padding:10,borderRadius:10,border:"none",fontWeight:"bold"}}>Post to {myHostel} 🔊</button></div>
{posts.map(p=><div key={p.id} style={{background:"white",padding:14,borderRadius:14,marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between"}}><div style={{display:"flex",gap:8}}><div style={{width:36,height:36,background:"#e5e7eb",borderRadius:18}}></div><div><div style={{fontWeight:"bold",fontSize:13}}>{p.name} ✓</div><div style={{fontSize:11,color:"#6b7280"}}>{p.tag} • {p.time}</div></div></div><button onClick={()=>shareWA(p.text,false)} style={{background:"#25D366",color:"white",border:"none",padding:"6px 10px",borderRadius:20,fontSize:10}}>💬 WhatsApp + Gate</button></div><div style={{marginTop:10}}>{p.text}</div><div style={{marginTop:10,display:"flex",gap:14,borderTop:"1px solid #f3f4f6",paddingTop:10}}><span onClick={()=>setShowReact(showReact===p.id?null:p.id)} style={{fontWeight:"bold",fontSize:12}}>{p.react} {p.rc} • 30 Reactions</span><span onClick={()=>setCommentFor(commentFor===p.id?null:p.id)} style={{fontWeight:"bold",fontSize:12}}>💬 Comment ({p.comments.length})</span><span onClick={()=>setShareFor(shareFor===p.id?null:p.id)} style={{fontWeight:"bold",fontSize:12}}>↗️ Share</span></div>
{showReact===p.id&&<div style={{marginTop:8,background:"white",border:"1px solid #eee",borderRadius:12,padding:8,display:"flex",gap:6,flexWrap:"wrap"}}>{reacts.map(r=><span key={r} onClick={()=>reactPost(p.id,r)} style={{fontSize:20,padding:4}}>{r}</span>)}</div>}
{commentFor===p.id&&<div style={{marginTop:10}}>{p.comments.map(c=><div key={c.id} style={{background:"#f3f4f6",padding:10,borderRadius:12,marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between"}}><div><b style={{fontSize:12}}>{c.name} {c.react}</b><div style={{fontSize:13}}>{c.text}</div>{c.voice&&<audio controls src={c.voice} style={{width:150,marginTop:6}}/>}</div><span style={{fontSize:11}}>{c.react} {c.rc}</span></div><div style={{display:"flex",gap:8,marginTop:6,flexWrap:"wrap"}}><span onClick={()=>{setReplyFor(c.id);setCommentTxt(`@${c.name} `)}} style={{fontSize:11,color:"#2563eb"}}>Reply</span><span onClick={()=>shareWA(c.text,true)} style={{fontSize:11,color:"#25D366"}}>WhatsApp</span>{c.name==="You"&&<><span onClick={()=>startEdit(c)} style={{fontSize:11,color:"#6b7280"}}>✏️ Edit</span><span onClick={()=>delComment(p.id,c.id)} style={{fontSize:11,color:"red"}}>🗑️ Delete</span></>}</div></div>)}
<div style={{marginTop:8,background:"white",border:"1px solid #e5e7eb",borderRadius:20,padding:"6px 10px",display:"flex",gap:6,alignItems:"center"}}><button onClick={()=>setRecFor("comment")} style={{border:"none",background:rec&&recFor==="comment"?"red":"#f3f4f6",borderRadius:15,padding:"5px 8px",fontSize:11}} onMouseDown={()=>startRec("comment")} onMouseUp={()=>{if(mrRef.current)mrRef.current.stop()}}>{rec&&recFor==="comment"?"⏹️ 1min":"🎤 1min"}</button><input value={commentTxt} onChange={e=>setCommentTxt(e.target.value)} placeholder={editId?"Edit comment...":"Comment..."} style={{flex:1,border:"none",outline:"none",fontSize:12}}/><button onClick={()=>{if(!commentTxt.trim())return;if(editId){setPosts(posts.map(po=>po.id!==p.id?po:{...po,comments:po.comments.map(cc=>cc.id===editId?{...cc,text:commentTxt}:cc)}));setEditId(null);setCommentTxt("")}else{setPosts(posts.map(po=>po.id!==p.id?po:{...po,comments:[...po.comments,{id:Date.now(),name:"You",text:commentTxt,react:"❤️",rc:0,liked:false}]}));setCommentTxt("")}push("Comment posted ✓","like")}} style={{background:"#2563eb",color:"white",border:"none",padding:"6px 12px",borderRadius:15,fontSize:11,fontWeight:"bold"}}>{editId?"Save":"Post"}</button></div></div></div>)}</div>}

{tab==="community"&&<div style={{padding:12}}><h2>🏠 Hostels - Join/Leave + Count</h2><div style={{marginTop:12,display:"flex",flexDirection:"column",gap:8}}>{hostels.map(h=><div key={h} style={{background:"white",padding:14,borderRadius:12,display:"flex",justifyContent:"space-between"}}><div><div style={{fontWeight:"bold",fontSize:13}}>🏠 {h}</div><div style={{fontSize:11,color:"#6b7280"}}>👥 {members[h]||100} members • {joined.includes(h)?"Joined ✓":"Not joined"}</div></div><button onClick={()=>toggleHostel(h)} style={{padding:"8px 14px",borderRadius:20,border:"none",background:joined.includes(h)?"#fee2e2":"#dcfce7",color:joined.includes(h)?"#dc2626":"#16a34a",fontWeight:"bold",fontSize:11}}>{joined.includes(h)?"Leave":"Join"}</button></div>)}</div></div>}

{tab==="market"&&<div style={{padding:12}}><h2>🛒 Market - Filter + Delete Sold</h2><div style={{background:"white",padding:10,borderRadius:12,marginTop:10,display:"flex",gap:6}}><button onClick={()=>setPrice("all")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:price==="all"?"#2563eb":"#f3f4f6",color:price==="all"?"white":"black",fontSize:11}}>All</button><button onClick={()=>setPrice("low")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:price==="low"?"#2563eb":"#f3f4f6",color:price==="low"?"white":"black",fontSize:11}}>Under ₦2k</button><button onClick={()=>setPrice("mid")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:price==="mid"?"#2563eb":"#f3f4f6",color:price==="mid"?"white":"black",fontSize:11}}>₦2k-10k</button><button onClick={()=>setPrice("high")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:price==="high"?"#2563eb":"#f3f4f6",color:price==="high"?"white":"black",fontSize:11}}>Above ₦10k</button></div><div style={{marginTop:10,display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{filtered.map(m=><div key={m.id} style={{background:m.sold?"#fee2e2":"white",padding:10,borderRadius:12,opacity:m.sold?0.6:1}}><div>{m.img} {m.name}</div><div style={{fontWeight:"bold"}}>{m.pt} {m.sold&&"SOLD"}</div><div style={{fontSize:11}}>{m.hostel}</div>{m.seller==="You"&&<div style={{display:"flex",gap:6,marginTop:6}}><button onClick={()=>setMarket(market.map(x=>x.id===m.id?{...x,sold:true}:x))} style={{flex:1,padding:6,borderRadius:8,border:"none",background:"#f59e0b",color:"white",fontSize:10}}>Sold</button><button onClick={()=>{if(confirm("Delete?"))setMarket(market.filter(x=>x.id!==m.id))}} style={{flex:1,padding:6,borderRadius:8,border:"none",background:"#ef4444",color:"white",fontSize:10}}>🗑️ Delete</button></div>}</div>)}</div></div>}

{tab==="chat"&&<div style={{display:"flex",flexDirection:"column",height:"85vh"}}><div style={{background:"white",padding:12,borderBottom:"1px solid #eee",display:"flex",justifyContent:"space-between"}}><span onClick={()=>setTab("feed")}>← Feed</span><b>💬 Chat - Voice Long, Video, Image</b></div><div style={{flex:1,padding:12,overflowY:"auto",display:"flex",flexDirection:"column",gap:8}}>{msgs.map(m=><div key={m.id} style={{alignSelf:m.from==="you"?"flex-end":"flex-start",background:m.from==="you"?"#2563eb":"white",color:m.from==="you"?"white":"black",padding:10,borderRadius:14,maxWidth:"75%"}}>{m.type==="voice"?<><audio controls src={m.url} style={{width:150}}/><div style={{fontSize:10}}>🎤 Voice - long</div></>:<div>{m.text}</div>}</div>)}</div><div style={{background:"white",padding:10,display:"flex",gap:6}}><button onClick={()=>{if(rec)mrRef.current?.stop();else startRec("chat")}} style={{background:rec&&recFor==="chat"?"red":"#f3f4f6",border:"none",padding:10,borderRadius:20}}>{rec&&recFor==="chat"?"⏹️ Stop Long":"🎤 Voice Long"}</button><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Message..." style={{flex:1,padding:10,borderRadius:20,border:"1px solid #eee"}}/><button onClick={()=>{if(!chatInput.trim())return;setMsgs([...msgs,{id:Date.now(),from:"you",text:chatInput,type:"text"}]);setChatInput("");setTimeout(()=>{setMsgs(v=>[...v,{id:Date.now()+1,from:"seller",text:"Ok boss 👍",type:"text"}]);push("New message 💬","message");setUnread(u=>u+1);playTone("message")},1000)}} style={{background:"#2563eb",color:"white",border:"none",padding:10,borderRadius:20}}>Send</button></div></div>}

{tab==="status"&&<div style={{padding:12}}><h2>📸 Status - WhatsApp Style</h2><div style={{marginTop:10}}><button onClick={()=>setShowStatus(true)} style={{width:"100%",padding:12,borderRadius:12,background:"#2563eb",color:"white",border:"none",fontWeight:"bold"}}>+ Add Status (as many as possible)</button><div style={{marginTop:12,display:"flex",flexDirection:"column",gap:8}}>{statusList.map((s,i)=><div key={i} onClick={()=>viewStatus(i)} style={{background:"white",padding:12,borderRadius:12}}><div style={{display:"flex",justifyContent:"space-between"}}><b>{s.ava} {s.name} • {s.items.length} status</b><span style={{fontSize:11}}>{s.items[0]?.views} views 👁️</span></div><div style={{fontSize:11,color:"#6b7280",marginTop:4}}>Tap to view → Like, Comment, Share to Timeline/Hostels/WhatsApp • See who liked/commented/shared</div></div>)}</div></div></div>}

{tab==="notifs"&&<div style={{padding:12}}><h2>🔔 Push Notifications (works closed) 🔊</h2><div style={{fontSize:11,color:"#6b7280"}}>Allow permission to get push even when app closed</div><div style={{marginTop:12,display:"flex",flexDirection:"column",gap:8}}>{notifs.map(n=><div key={n.id} style={{background:"white",padding:12,borderRadius:12}}><b style={{fontSize:12}}>{n.text} 🔊</b><div style={{fontSize:10,color:"#6b7280"}}>{n.time} • Push + Tone even when closed</div></div>)}</div><button onClick={()=>push("Test push even when app closed 🔊","mention")} style={{marginTop:12,width:"100%",padding:12,borderRadius:12,background:"#111827",color:"white",border:"none",fontWeight:"bold"}}>Test Push + Tone 🔊</button></div>}

<div style={{position:"fixed",bottom:0,left:0,right:0,background:"white",borderTop:"1px solid #eee",display:"flex",justifyContent:"space-around",padding:"10px 0",fontSize:10,fontWeight:"bold"}}><span onClick={()=>setTab("feed")} style={{color:tab==="feed"?"#2563eb":"#9ca3af"}}>📱 Feed</span><span onClick={()=>setTab("status")} style={{color:tab==="status"?"#2563eb":"#9ca3af"}}>📸 Status {statusList.reduce((a,b)=>a+b.items.length,0)}</span><span onClick={()=>setTab("community")} style={{color:tab==="community"?"#2563eb":"#9ca3af"}}>🏠 Hostels ({joined.length})</span><span onClick={()=>setTab("market")} style={{color:tab==="market"?"#2563eb":"#9ca3af"}}>🛒 Market</span><span onClick={()=>setTab("chat")} style={{color:tab==="chat"?"#2563eb":"#9ca3af"}}>💬 Chat ({unread})</span></div>
</div>
)}
