"use client"
import { useState } from "react"
export default function Home(){
const [tab,setTab]=useState("feed")
const [myHostel,setMyHostel]=useState("W4 Annex")
const [isVerified]=useState(true)
const [showMarketPost,setShowMarketPost]=useState(false)
const [newItem,setNewItem]=useState({name:"",price:"",imgUrl:null})
const [activeChat,setActiveChat]=useState(null)
const [messages,setMessages]=useState([])
const [chatInput,setChatInput]=useState("")
const [feedFilter,setFeedFilter]=useState("all")
const [commentFor,setCommentFor]=useState(null)
const [commentTxt,setCommentTxt]=useState("")
const [replyFor,setReplyFor]=useState(null)
const [shareFor,setShareFor]=useState(null)
const [showStickers,setShowStickers]=useState(false)
const [showMentions,setShowMentions]=useState(false)
const [notifications,setNotifications]=useState([{id:1,text:"Favour E. mentioned you in NDDC Male",time:"2m",read:false},{id:2,text:"John liked your comment",time:"5m",read:false}])

const stickers=["😂","😭","❤️","🔥","😍","🙏","💀","😂😂","🎉","👏","😎","🥺"]
const usersToMention=["Favour E.","John","Campus Buka","Ekom Imman","Sarah G.","David O.","You"]
const faculties=["Agriculture","Arts","Science","Engineering"]
const hostels=["NDDC Male","NDDC Female","W2A","W5","W4 Annex","Town Campus","NEEDS","New NDDC","Medical Hostel","Haldeen","OFF CAMPUS"]

const [posts,setPosts]=useState([
{id:1,name:"Favour E.",tag:"19/AG/BCH/123 • Agriculture",time:"2h",text:"Who has GST 111 past questions? 😭",likes:13,liked:true,cat:"general",verified:true,comments:[{id:101,name:"You",text:"I get am, DM me",likes:2,liked:false,sticker:null,img:null,replies:[{name:"You",text:"@You where you dey",likes:0,liked:false}]},{id:102,name:"John",text:"Same here",likes:1,liked:false,sticker:null,img:null,replies:[{name:"Favour",text:"Send to my hostel NDDC",likes:0,liked:false}]}]},
{id:2,name:"Campus Buka",tag:"Vendor • Food Review",time:"5h",text:"Jollof + Chicken ₦1500 today! Free delivery NDDC",likes:46,liked:true,cat:"food",verified:true,comments:[]},
])

const [market,setMarket]=useState([{id:1,name:"Jollof + Chicken",price:"₦1500",seller:"Campus Buka",img:"🍛",imgUrl:null,verified:true,hostel:"NDDC Male"}])
const [txt,setTxt]=useState("")
const likePost=(id)=>{setPosts(posts.map(p=>p.id===id?{...p,likes:p.liked?p.likes-1:p.likes+1,liked:!p.liked}:p))}
const likeComment=(postId,commentId,isReply=false,replyIdx=null)=>{setPosts(posts.map(p=>{if(p.id!==postId) return p; return {...p,comments:p.comments.map(c=>{ if(c.id!==commentId) return c; if(isReply){ const newReplies=[...c.replies]; newReplies[replyIdx]={...newReplies[replyIdx],likes:newReplies[replyIdx].liked?newReplies[replyIdx].likes-1:newReplies[replyIdx].likes+1,liked:!newReplies[replyIdx].liked}; return {...c,replies:newReplies} } return {...c,likes:c.liked?c.likes-1:c.likes+1,liked:!c.liked} })} }))}
const handleImg=(e)=>{const f=e.target.files[0]; if(f){const r=new FileReader(); r.onload=(ev)=>setNewItem({...newItem,imgUrl:ev.target.result}); r.readAsDataURL(f)}}
const handleCommentImg=(e)=>{const f=e.target.files[0]; if(f){const r=new FileReader(); r.onload=(ev)=>{ addCommentWithExtra(posts.find(p=>p.id===commentFor),null,ev.target.result,null) }; r.readAsDataURL(f)}}
const addCommentWithExtra=(postObj, sticker=null, img=null, customText=null)=>{
const textToUse = customText!==null? customText : commentTxt
if(!textToUse.trim() &&!sticker &&!img) return
const hasMention = textToUse.includes("@")
if(hasMention){ const mentioned = usersToMention.find(u=>textToUse.includes("@"+u.split(" ")[0])); if(mentioned){ setNotifications([{id:Date.now(),text:`You mentioned ${mentioned} in comment`,time:"now",read:false},...notifications]) } }
setPosts(posts.map(p=>{ if(p.id!==postObj.id) return p; const newC={id:Date.now(),name:"You",text:textToUse,likes:0,liked:false,sticker,img,replies:[]}; if(replyFor){ const parent=p.comments.find(c=>c.id===replyFor); if(parent){ parent.replies.push({name:"You",text:textToUse,likes:0,liked:false,sticker,img}); setReplyFor(null); setCommentTxt(""); setShowMentions(false); return p } } return {...p,comments:[...p.comments,newC]} })); setCommentTxt(""); setShowStickers(false); setShowMentions(false)
}
const sharePost=(postId,target)=>{ const post=posts.find(p=>p.id===postId); const newP={...post,id:Date.now(),tag:`Shared to ${target} • ${myHostel}`,time:"now"}; setPosts([newP,...posts]); setShareFor(null); setNotifications([{id:Date.now(),text:`Your post shared to ${target} ✓`,time:"now",read:false},...notifications]) }

return(
<div style={{minHeight:"100vh",background:"#f5f5f5",paddingBottom:80}}>
<div style={{background:"white",padding:"12px 16px",borderBottom:"1px solid #eee",display:"flex",justifyContent:"space-between",position:"sticky",top:0,zIndex:20}}><b>🎓 Uniuyo Connect</b><div style={{display:"flex",gap:8}}><span onClick={()=>setTab("notifications")} style={{fontSize:18,position:"relative"}}>🔔{notifications.filter(n=>!n.read).length>0&&<span style={{position:"absolute",top:-4,right:-6,background:"red",color:"white",fontSize:8,padding:"2px 5px",borderRadius:10}}>{notifications.filter(n=>!n.read).length}</span>}</span><span style={{fontSize:10,background:"#dcfce7",padding:"4px 8px",borderRadius:20}}>✓ Verified</span></div></div>

{tab==="feed"&&<><div style={{background:"white",margin:12,padding:12,borderRadius:16}}><div style={{display:"flex",gap:4,marginBottom:8}}><button onClick={()=>setShowMentions(!showMentions)} style={{padding:"6px 10px",borderRadius:20,border:"1px solid #e5e7eb",background:"white",fontSize:11}}> @ Mention</button><span style={{fontSize:11,color:"#6b7280",paddingTop:6}}>Tip: Type @ to mention anywhere</span></div><textarea value={txt} onChange={e=>{setTxt(e.target.value); if(e.target.value.includes("@")) setShowMentions(true)}} placeholder={`What's happening in ${myHostel}? Use @ to mention`} style={{width:"100%",background:"#f3f4f6",border:"none",padding:12,borderRadius:12,outline:"none"}} rows={2}/>{showMentions&&<div style={{background:"white",border:"1px solid #eee",borderRadius:10,marginTop:6,padding:6}}>{usersToMention.map(u=><div key={u} onClick={()=>{setTxt(txt+"@"+u.split(" ")[0]+" "); setShowMentions(false); setNotifications([{id:Date.now(),text:`You will notify ${u}`,time:"now",read:false},...notifications])}} style={{padding:6,fontSize:12}}>👤 {u}</div>)}</div>}<button onClick={()=>{if(txt.trim()){ const hasMen=txt.includes("@"); if(hasMen) setNotifications([{id:Date.now(),text:`Post mentioning someone in ${myHostel}`,time:"now",read:false},...notifications]); setPosts([{id:Date.now(),name:"You",tag:`16/AG/AS/303 • ${myHostel}`,time:"now",text:txt,likes:0,liked:false,cat:"general",verified:isVerified,comments:[]},...posts]);setTxt("")}}} style={{marginTop:8,width:"100%",background:"#2563eb",color:"white",padding:10,borderRadius:10,border:"none",fontWeight:"bold"}}>Post to {myHostel}</button></div>
<div style={{padding:"0 12px",display:"flex",flexDirection:"column",gap:10}}>{posts.map(p=><div key={p.id} style={{background:"white",padding:14,borderRadius:14}}><div style={{display:"flex",gap:8}}><div style={{width:36,height:36,background:"#e5e7eb",borderRadius:18}}></div><div><div style={{fontWeight:"bold",fontSize:13}}>{p.name} {p.verified?"✓":""}</div><div style={{fontSize:11,color:"#6b7280"}}>{p.tag} • {p.time}</div></div></div><div style={{marginTop:10,fontSize:14}}>{p.text}</div><div style={{marginTop:10,display:"flex",gap:18,fontSize:12,color:"#6b7280",borderTop:"1px solid #f3f4f6",paddingTop:10}}><span onClick={()=>likePost(p.id)} style={{color:p.liked?"red":"",fontWeight:"bold"}}>{p.liked?"❤️":"🤍"} {p.likes}</span><span onClick={()=>setCommentFor(commentFor===p.id?null:p.id)} style={{fontWeight:"bold"}}>💬 Comment {p.comments.length>0?`(${p.comments.length})`:""}</span><span onClick={()=>setShareFor(shareFor===p.id?null:p.id)} style={{fontWeight:"bold"}}>↗️ Share</span></div>
{shareFor===p.id&&<div style={{marginTop:10,background:"#f9fafb",padding:10,borderRadius:10}}><div style={{fontSize:11,fontWeight:"bold"}}>Share to:</div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:6}}><button onClick={()=>sharePost(p.id,"Timeline")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:"#2563eb",color:"white",fontSize:11}}>Timeline</button>{hostels.map(h=><button key={h} onClick={()=>sharePost(p.id,h)} style={{padding:"6px 10px",borderRadius:20,border:"1px solid #e5e7eb",background:"white",fontSize:11}}>🏠 {h}</button>)}</div></div>}
{commentFor===p.id&&<div style={{marginTop:10}}>{p.comments.map(c=><div key={c.id} style={{background:"#f3f4f6",padding:10,borderRadius:12,marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:12,fontWeight:"bold"}}>{c.name}</div><div style={{fontSize:13}}>{c.text} {c.sticker&&<span style={{fontSize:18}}>{c.sticker}</span>}</div>{c.img&&<img src={c.img} style={{width:100,height:80,objectFit:"cover",borderRadius:8,marginTop:6}}/>}</div><span onClick={()=>likeComment(p.id,c.id)} style={{fontSize:11,color:c.liked?"red":"#6b7280",fontWeight:"bold"}}>{c.liked?"❤️":"🤍"} {c.likes}</span></div><div style={{display:"flex",gap:12,marginTop:6}}><span onClick={()=>{setReplyFor(c.id); setCommentTxt(`@${c.name} `)}} style={{fontSize:11,color:"#2563eb"}}>Reply</span><span style={{fontSize:11,color:"#6b7280"}}>Like ({c.likes})</span></div>{c.replies.map((r,i)=><div key={i} style={{marginLeft:12,marginTop:8,background:"white",padding:8,borderRadius:10,display:"flex",justifyContent:"space-between"}}><div><b style={{fontSize:11}}>{r.name}:</b><span style={{fontSize:12}}> {r.text} {r.sticker}</span>{r.img&&<img src={r.img} style={{width:80,height:60,objectFit:"cover",borderRadius:6,marginTop:4}}/>}</div><span onClick={()=>likeComment(p.id,c.id,true,i)} style={{fontSize:10,color:r.liked?"red":"#9ca3af"}}>{r.liked?"❤️":"🤍"} {r.likes}</span></div>)}</div>)}
<div style={{marginTop:8,background:"white",border:"1px solid #e5e7eb",borderRadius:20,padding:"6px 10px",display:"flex",alignItems:"center",gap:6}}><button onClick={()=>setShowMentions(!showMentions)} style={{border:"none",background:"#f3f4f6",borderRadius:15,padding:"4px 8px",fontSize:12}}>@</button><button onClick={()=>setShowStickers(!showStickers)} style={{border:"none",background:"#f3f4f6",borderRadius:15,padding:"4px 8px"}}>😊</button><label style={{border:"none",background:"#f3f4f6",borderRadius:15,padding:"4px 8px",fontSize:12}}>📷<input type="file" accept="image/*" onChange={handleCommentImg} style={{display:"none"}}/></label><input value={commentTxt} onChange={e=>{setCommentTxt(e.target.value); if(e.target.value.includes("@")) setShowMentions(true)}} placeholder={replyFor?"Reply with @...":"Comment, @mention, add pic/sticker..."} style={{flex:1,border:"none",outline:"none",fontSize:12,background:"transparent"}}/><button onClick={()=>addCommentWithExtra(p,null,null,commentTxt)} style={{background:"#2563eb",color:"white",border:"none",padding:"6px 12px",borderRadius:15,fontSize:11,fontWeight:"bold"}}>Post</button></div>
{showStickers&&<div style={{marginTop:8,background:"white",padding:8,borderRadius:12,display:"flex",gap:8,flexWrap:"wrap"}}>{stickers.map(s=><span key={s} onClick={()=>addCommentWithExtra(p,s,null,commentTxt)} style={{fontSize:20,padding:4}}>{s}</span>)}</div>}
{showMentions&&<div style={{marginTop:6,background:"white",border:"1px solid #eee",borderRadius:10,padding:6,maxHeight:120,overflowY:"auto"}}><div style={{fontSize:10,color:"#6b7280",marginBottom:4}}>Mention someone - they get notification 🔔</div>{usersToMention.map(u=><div key={u} onClick={()=>{setCommentTxt(commentTxt+"@"+u.split(" ")[0]+" "); setShowMentions(false)}} style={{padding:6,fontSize:12,display:"flex",justifyContent:"space-between"}}><span>👤 {u}</span><span style={{color:"#2563eb",fontSize:10}}>Notify</span></div>)}</div>}
</div>}</div>)}</div></>}

{tab==="notifications"&&<div style={{padding:12}}><h2 style={{fontWeight:"bold"}}>🔔 Notifications</h2><div style={{display:"flex",flexDirection:"column",gap:8,marginTop:12}}>{notifications.map(n=><div key={n.id} style={{background:n.read?"white":"#eff6ff",padding:12,borderRadius:12,display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:12,fontWeight:"bold"}}>{n.text}</div><div style={{fontSize:10,color:"#6b7280"}}>{n.time} • From @mention, comment like, share</div></div><span onClick={()=>setNotifications(notifications.map(x=>x.id===n.id?{...x,read:true}:x))} style={{fontSize:10,color:"#2563eb"}}>{n.read?"Read":"Mark read"}</span></div>)}</div><button onClick={()=>setTab("feed")} style={{marginTop:12,width:"100%",background:"#2563eb",color:"white",border:"none",padding:10,borderRadius:10}}>Back to Feed</button></div>}

{tab==="community"&&<div style={{padding:12}}><h3>🏠 Communities - @mention works here too</h3><div style={{background:"white",padding:12,borderRadius:12,marginTop:8}}><div style={{fontSize:11}}>Your hostel: {myHostel}</div><select value={myHostel} onChange={e=>setMyHostel(e.target.value)} style={{width:"100%",padding:8,marginTop:6,borderRadius:8}}>{hostels.map(h=><option key={h}>{h}</option>)}</select></div></div>}
{tab==="market"&&<div style={{padding:12}}><h3>🛒 Market - Chat in app + Verified only</h3><div style={{background:"white",padding:12,borderRadius:12,marginTop:8,display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{market.map(m=><div key={m.id} style={{background:"#f9fafb",padding:10,borderRadius:10}}><div>{m.name} - {m.price}</div><button onClick={()=>{setActiveChat(m); setTab("chat")}} style={{marginTop:6,background:"#2563eb",color:"white",border:"none",padding:6,borderRadius:6,fontSize:11}}>Chat Seller</button></div>)}</div></div>}
{tab==="chat"&&<div style={{padding:12}}><button onClick={()=>setTab("feed")} style={{marginBottom:10}}>← Back</button><h3>💬 Chat with {activeChat?.name}</h3><div style={{background:"white",padding:12,borderRadius:12,height:300,overflowY:"auto"}}>{messages.filter(m=>m.item===activeChat?.name).map(msg=><div key={msg.id} style={{background:msg.from==="you"?"#2563eb":"#f3f4f6",color:msg.from==="you"?"white":"black",padding:8,borderRadius:12,marginBottom:6,maxWidth:"70%",alignSelf:msg.from==="you"?"flex-end":"flex-start"}}>{msg.text}</div>)}</div><div style={{display:"flex",gap:6,marginTop:10}}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Chat buyer/seller @mention works" style={{flex:1,padding:10,borderRadius:20,border:"1px solid #eee"}}/><button onClick={()=>{ if(chatInput.includes("@")) setNotifications([{id:Date.now(),text:`You mentioned someone in chat`,time:"now",read:false},...notifications]); setMessages([...messages,{id:Date.now(),from:"you",text:chatInput,item:activeChat?.name}]); setChatInput("")}} style={{background:"#2563eb",color:"white",border:"none",padding:10,borderRadius:20}}>Send</button></div></div>}
{tab==="events"&&<div style={{padding:12}}><h3>📅 Events + @mention</h3></div>}
{tab==="profile"&&<div style={{padding:12}}><h3>👤 Profile - {myHostel} ✓</h3></div>}

<div style={{position:"fixed",bottom:0,left:0,right:0,background:"white",borderTop:"1px solid #eee",display:"flex",justifyContent:"space-around",padding:"10px 0",fontSize:10,fontWeight:"bold"}}><span onClick={()=>setTab("feed")} style={{color:tab==="feed"?"#2563eb":"#9ca3af"}}>Feed</span><span onClick={()=>setTab("community")} style={{color:tab==="community"?"#2563eb":"#9ca3af"}}>Community</span><span onClick={()=>setTab("market")} style={{color:tab==="market"?"#2563eb":"#9ca3af"}}>Market</span><span onClick={()=>setTab("notifications")} style={{color:tab==="notifications"?"#2563eb":"#9ca3af"}}>🔔 Alerts</span><span onClick={()=>setTab("profile")} style={{color:tab==="profile"?"#2563eb":"#9ca3af"}}>Profile</span></div>
</div>
)}
