"use client"
import { useState, useRef, useEffect } from "react"
export default function Home(){
const [tab,setTab]=useState("feed")
const [myHostel,setMyHostel]=useState("W4 Annex")
const [joinedHostels,setJoinedHostels]=useState(["W4 Annex"])
const [hostelMembers,setHostelMembers]=useState({ "W4 Annex": 243, "NDDC Male": 312, "NDDC Female": 298, "W2A": 180, "W5": 210, "Town Campus": 165, "NEEDS": 120, "New NDDC": 200, "Medical Hostel": 150, "Haldeen": 190, "OFF CAMPUS": 400 })
const [notifications,setNotifications]=useState([{id:1,text:"Favour mentioned you @You",time:"2m",read:false,type:"mention"}])
const [showPopup,setShowPopup]=useState(null)
const [unreadMsgs,setUnreadMsgs]=useState(2)
const [statusList,setStatusList]=useState([
{id:1,name:"You",avatar:"🧑",items:[{id:101,type:"text",content:"In W4 Annex reading GST 😭",time:"10m",likes:12,views:45,liked:false,comments:[]}]},
{id:2,name:"Favour E.",avatar:"👩",items:[{id:201,type:"image",content:"https://picsum.photos/300/500?1",caption:"My hostel view!",time:"30m",likes:23,views:89,liked:true,comments:[{name:"You",text:"Fine view!"}]}]},
{id:3,name:"Campus Buka",avatar:"🍛",items:[{id:301,type:"text",content:"Jollof ready! ₦1500",time:"1h",likes:56,views:120,liked:false,comments:[]}]}
])
const [activeStatus,setActiveStatus]=useState(null)
const [activeStatusIdx,setActiveStatusIdx]=useState(0)
const [newStatusText,setNewStatusText]=useState("")
const [showStatusInput,setShowStatusInput]=useState(false)
const [commentFor,setCommentFor]=useState(null)
const [commentTxt,setCommentTxt]=useState("")
const [editComment,setEditComment]=useState(null)
const [replyFor,setReplyFor]=useState(null)
const [shareFor,setShareFor]=useState(null)
const [showReactions,setShowReactions]=useState(null)
const [showStickers,setShowStickers]=useState(false)
const [showMentions,setShowMentions]=useState(false)
const [isRecording,setIsRecording]=useState(false)
const [recordingFor,setRecordingFor]=useState(null)
const mediaRecorderRef=useRef(null)
const [priceFilter,setPriceFilter]=useState("all")

const reactions30=["❤️","👍","😂","😭","😍","🔥","🙏","💀","🎉","👏","😎","🥺","🤣","❤️‍🔥","💯","😡","😮","🥰","🤩","😴","🤔","😏","🫡","👌","🫶","✨","💔","😇","🤯","🥲"]

const hostels=["NDDC Male","NDDC Female","W2A","W5","W4 Annex","Town Campus","NEEDS","New NDDC","Medical Hostel","Haldeen","OFF CAMPUS"]

const playTone=(type)=>{try{const ctx=new (window.AudioContext||window.webkitAudioContext)(); const o=ctx.createOscillator(); const g=ctx.createGain(); o.connect(g); g.connect(ctx.destination); o.frequency.value=type==="mention"?880:type==="message"?650:500; g.gain.value=0.35; o.start(); g.gain.exponentialRampToValueAtTime(0.01,ctx.currentTime+0.6); o.stop(ctx.currentTime+0.6)}catch(e){} if("vibrate" in navigator) navigator.vibrate(200)}
const pushNotif=(text,type)=>{setNotifications(p=>[{id:Date.now(),text,time:"now",read:false,type},...p]); setShowPopup({text,type}); playTone(type); setTimeout(()=>setShowPopup(null),3500); if("Notification" in window && Notification.permission==="granted"){ new Notification("Uniuyo Connect 🔊",{body:text}) }}

useEffect(()=>{ if("Notification" in window && Notification.permission!=="granted"){ Notification.requestPermission() } },[])

const [posts,setPosts]=useState([
{id:1,name:"Favour E.",tag:"19/AG/BCH/123 • Agriculture",time:"2h",text:"Who has GST 111 past questions? 😭",reaction:"❤️",reactionsCount:13,liked:true,cat:"general",verified:true,comments:[
{id:101,name:"You",text:"I get am, DM me",reaction:"👍",reactionsCount:2,liked:false,img:null,voice:null,replies:[]},
{id:102,name:"John",text:"Same here",reaction:"😂",reactionsCount:1,liked:false,img:null,voice:null,replies:[]}
]},
])

const [market,setMarket]=useState([
{id:1,name:"Jollof + Chicken",price:1500,priceText:"₦1500",seller:"Campus Buka",img:"🍛",imgUrl:null,verified:true,hostel:"NDDC Male",sold:false},
{id:2,name:"Power Bank 20k mAh",price:8000,priceText:"₦8000",seller:"You",img:"🔋",imgUrl:null,verified:true,hostel:"W4 Annex",sold:false}
])

const [messages,setMessages]=useState([
{id:1,from:"seller",text:"Jollof still available? 😋",type:"text",item:"Jollof + Chicken"},
{id:2,from:"you",text:"Yes boss, coming",type:"text",item:"Jollof + Chicken"}
])
const [chatInput,setChatInput]=useState("")
const [activeChat,setActiveChat]=useState({name:"Jollof + Chicken",seller:"Campus Buka"})
const [txt,setTxt]=useState("")

// EDIT / DELETE COMMENT
const deleteComment=(postId,cId)=>{if(confirm("Delete comment?")){setPosts(posts.map(p=>p.id!==postId?p:{...p,comments:p.comments.filter(c=>c.id!==cId)})); pushNotif("Comment deleted 🗑️","like")}}
const startEditComment=(c)=>{setEditComment(c.id); setCommentTxt(c.text)}
const saveEditComment=(postId)=>{setPosts(posts.map(p=>p.id!==postId?p:{...p,comments:p.comments.map(c=>c.id===editComment?{...c,text:commentTxt}:c)})); setEditComment(null); setCommentTxt(""); pushNotif("Comment edited ✏️","like")}

// 30 REACTIONS
const reactPost=(postId,emoji)=>{setPosts(posts.map(p=>p.id===postId?{...p,reaction:emoji,reactionsCount:p.reaction===emoji?p.reactionsCount:p.reactionsCount+1,liked:true}:p)); setShowReactions(null); pushNotif(`You reacted ${emoji} to post`,"like"); playTone("like")}
const reactComment=(postId,cId,emoji)=>{setPosts(posts.map(p=>p.id!==postId?p:{...p,comments:p.comments.map(c=>c.id===cId?{...c,reaction:emoji,reactionsCount:(c.reaction===emoji?c.reactionsCount:c.reactionsCount+1),liked:true}:c)})); setShowReactions(null)}

// HOSTEL JOIN / LEAVE
const toggleHostel=(h)=>{if(joinedHostels.includes(h)){setJoinedHostels(joinedHostels.filter(x=>x!==h)); setHostelMembers({...hostelMembers,[h]:hostelMembers[h]-1}); pushNotif(`Left ${h} 👋`,"like")} else {setJoinedHostels([...joinedHostels,h]); setHostelMembers({...hostelMembers,[h]:(hostelMembers[h]||0)+1}); pushNotif(`Joined ${h} 🎉 🔊`,"mention"); playTone("mention")}}

// STATUS
const addStatus=()=>{if(!newStatusText.trim()) return; const newItem={id:Date.now(),type:"text",content:newStatusText,time:"now",likes:0,views:1,liked:false,comments:[]}; setStatusList(s=>{const me=s.find(x=>x.name==="You"); if(me){return s.map(x=>x.name==="You"?{...x,items:[newItem,...x.items]}:x)} else {return [{name:"You",avatar:"🧑",items:[newItem]},...s]}}); setNewStatusText(""); setShowStatusInput(false); pushNotif("Status added! Others can like, share, reply 🔊","mention")}
const likeStatus=(userIdx,itemIdx)=>{setStatusList(s=>s.map((u,ui)=>ui!==userIdx?u:{...u,items:u.items.map((it,ii)=>ii!==itemIdx?it:{...it,likes:it.liked?it.likes-1:it.likes+1,liked:!it.liked})}))); playTone("like")}
const shareStatusTo=(userIdx,itemIdx,target)=>{const item=statusList[userIdx].items[itemIdx]; if(target==="timeline"){setPosts([{id:Date.now(),name:"You",tag:`Shared status • ${myHostel}`,time:"now",text:item.content,reaction:"❤️",reactionsCount:0,liked:false,cat:"general",verified:true,comments:[]},...posts]); pushNotif(`Status reshared to Timeline ↗️`,"mention")} else if(target==="whatsapp"){const shareText=`${item.content} - View on Uniuyo Connect: https://t-wine.vercel.app/?register=1`; window.open(`https://wa.me/?text=${encodeURIComponent(shareText)}`,"_blank")} else {pushNotif(`Status shared to ${target} 🏠`,"mention")}}
const viewStatus=(idx)=>{setActiveStatus(idx); setActiveStatusIdx(0); setStatusList(s=>s.map((u,i)=>i!==idx?u:{...u,items:u.items.map(it=>({...it,views:it.views+1}))}))}

// VOICE NOTE
const startRecording=(forWhere)=>{setIsRecording(true); setRecordingFor(forWhere); playTone("message"); navigator.mediaDevices.getUserMedia({audio:true}).then(stream=>{const mr=new MediaRecorder(stream); mediaRecorderRef.current=mr; const chunks=[]; mr.ondataavailable=e=>chunks.push(e.data); mr.onstop=()=>{const blob=new Blob(chunks,{type:"audio/webm"}); const url=URL.createObjectURL(blob); if(forWhere==="chat"){setMessages([...messages,{id:Date.now(),from:"you",text:"🎤 Voice note",type:"voice",url,duration:"0:15",item:activeChat?.name}]); pushNotif("Voice note sent 🎤 🔊","message")} else {addCommentWithVoice(posts.find(p=>p.id===commentFor),url)}; setIsRecording(false)}; mr.start(); setTimeout(()=>{if(mr.state==="recording") mr.stop()}, forWhere==="comment"?60000:300000) }).catch(()=>{alert("Mic permission needed"); setIsRecording(false)})}
const stopRecording=()=>{if(mediaRecorderRef.current) mediaRecorderRef.current.stop()}
const addCommentWithVoice=(postObj,voiceUrl)=>{setPosts(posts.map(p=>p.id!==postObj.id?p:{...p,comments:[...p.comments,{id:Date.now(),name:"You",text:"🎤 Voice comment (1min max)",reaction:"🎤",reactionsCount:0,liked:false,img:null,voice:voiceUrl,replies:[]}]})); pushNotif("Voice comment posted 🎤","mention")}

// WHATSAPP SHARE WITH REGISTER GATE
const shareToWhatsapp=(text,isComment=false)=>{const registerLink="https://t-wine.vercel.app/?ref=whatsapp&register=1"; const msg=`${text}\n\n👀 View full ${isComment?"comment":"post"} + reply on Uniuyo Connect:\n${registerLink}\n\n🔔 Mention with tone 🔊 | 💬 Chat in app | 🏠 Hostel groups`; window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,"_blank"); pushNotif("Shared to WhatsApp - visitors need to register 🔐","mention")}

// MARKET FILTER & DELETE
const filteredMarket=market.filter(m=>{if(priceFilter==="low") return m.price<2000; if(priceFilter==="mid") return m.price>=2000 && m.price<=10000; if(priceFilter==="high") return m.price>10000; return true})
const deleteMarketItem=(id)=>{if(confirm("Delete sold item?")) setMarket(market.filter(x=>x.id!==id))}
const markSold=(id)=>{setMarket(market.map(m=>m.id===id?{...m,sold:true}:m)); pushNotif("Item marked as sold ✓","like")}

const addComment=(postObj,sticker=null,img=null,text=null)=>{
const t=text!==null?text:commentTxt
if(!t.trim()&&!sticker&&!img) return
if(editComment){saveEditComment(postObj.id); return}
setPosts(posts.map(p=>{
if(p.id!==postObj.id) return p
const newC={id:Date.now(),name:"You",text:t,reaction:"❤️",reactionsCount:0,liked:false,sticker,img,voice:null,replies:[]}
if(replyFor){const parent=p.comments.find(c=>c.id===replyFor); if(parent){parent.replies.push({name:"You",text:t}); setReplyFor(null); setCommentTxt(""); return p}}
return {...p,comments:[...p.comments,newC]}
})); setCommentTxt(""); setShowStickers(false); pushNotif("Comment posted ✓","like"); playTone("mention")
}

return(
<div style={{minHeight:"100vh",background:"#f5f5f5",paddingBottom:90}}>
{showPopup&&<div style={{position:"fixed",top:65,left:10,right:10,background:"#0f172a",color:"white",padding:14,borderRadius:14,zIndex:999,display:"flex",justifyContent:"space-between"}}><div><b>🔔 {showPopup.type==="message"?"New Message 🔊":"Notification 🔊"}</b><div style={{fontSize:11,marginTop:2}}>{showPopup.text}</div></div><span>🔊</span></div>}

<div style={{background:"white",padding:"12px 16px",borderBottom:"1px solid #eee",display:"flex",justifyContent:"space-between",position:"sticky",top:0,zIndex:30}}><b>🎓 Uniuyo Connect</b><div style={{display:"flex",gap:10,alignItems:"center"}}><span onClick={()=>setTab("status")} style={{fontSize:18}}>📸</span><span onClick={()=>setTab("chat")} style={{position:"relative",fontSize:18}}>💬{unreadMsgs>0&&<span style={{position:"absolute",top:-8,right:-10,background:"red",color:"white",fontSize:9,padding:"2px 6px",borderRadius:10}}>{unreadMsgs}</span>}</span><span onClick={()=>setTab("notifs")} style={{position:"relative",fontSize:18}}>🔔{notifications.filter(n=>!n.read).length>0&&<span style={{position:"absolute",top:-8,right:-8,background:"red",color:"white",fontSize:9,padding:"2px 5px",borderRadius:10}}>{notifications.filter(n=>!n.read).length}</span>}</span></div></div>

{/* STATUS BAR LIKE WHATSAPP */}
{tab==="feed"&&<div style={{background:"white",padding:"10px 12px",display:"flex",gap:12,overflowX:"auto",borderBottom:"1px solid #f3f4f6"}}>{statusList.map((s,i)=><div key={i} onClick={()=>viewStatus(i)} style={{minWidth:60,textAlign:"center"}}><div style={{width:56,height:56,borderRadius:28,border:s.name==="You"?"2px dashed #2563eb":"3px solid #10b981",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,background:"#f3f4f6"}}>{s.avatar}<span style={{position:"absolute",marginLeft:20,marginTop:20,fontSize:10,background:"#2563eb",color:"white",borderRadius:10,padding:"1px 4px"}}>{s.items.length}</span></div><div style={{fontSize:10,marginTop:4,fontWeight:"bold"}}>{s.name}</div><div style={{fontSize:9,color:"#6b7280"}}>{s.items[0]?.views} views</div></div>)}<div onClick={()=>setShowStatusInput(true)} style={{minWidth:60,textAlign:"center"}}><div style={{width:56,height:56,borderRadius:28,background:"#e5e7eb",display:"flex",alignItems:"center",justifyContent:"center",fontSize:24}}>+</div><div style={{fontSize:10}}>Add Status</div></div></div>}

{showStatusInput&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.8)",zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><div style={{background:"white",padding:20,borderRadius:16,width:"100%",maxWidth:320}}><h3>Add Status (like WhatsApp)</h3><textarea value={newStatusText} onChange={e=>setNewStatusText(e.target.value)} placeholder="What's on your mind? Others can like, reshare, reply" style={{width:"100%",padding:12,borderRadius:12,border:"1px solid #eee",marginTop:10}} rows={3}/><div style={{display:"flex",gap:8,marginTop:10}}><button onClick={()=>setShowStatusInput(false)} style={{flex:1,padding:10,borderRadius:10,border:"1px solid #eee",background:"white"}}>Cancel</button><button onClick={addStatus} style={{flex:1,padding:10,borderRadius:10,border:"none",background:"#2563eb",color:"white",fontWeight:"bold"}}>Post Status 🔊</button></div><div style={{fontSize:10,color:"#6b7280",marginTop:8}}>You can add as many status as possible • Others see who viewed, liked, commented</div></div></div>}

{activeStatus!==null&&<div style={{position:"fixed",inset:0,background:"black",zIndex:200,color:"white",display:"flex",flexDirection:"column"}}><div style={{padding:12,display:"flex",justifyContent:"space-between",alignItems:"center"}}><span onClick={()=>setActiveStatus(null)}>✕ Close</span><span style={{fontSize:12}}>{activeStatusIdx+1}/{statusList[activeStatus]?.items.length} • {statusList[activeStatus]?.items[activeStatusIdx]?.views} views 👁️</span></div><div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",padding:20,textAlign:"center"}}><div><div style={{fontSize:22}}>{statusList[activeStatus]?.items[activeStatusIdx]?.content}</div><div style={{fontSize:12,marginTop:10,color:"#9ca3af"}}>{statusList[activeStatus]?.items[activeStatusIdx]?.time}</div></div></div><div style={{padding:12,background:"rgba(255,255,255,0.1)"}}><div style={{display:"flex",justifyContent:"space-around",marginBottom:12}}><span onClick={()=>likeStatus(activeStatus,activeStatusIdx)} style={{fontSize:18}}>{statusList[activeStatus]?.items[activeStatusIdx]?.liked?"❤️":"🤍"} {statusList[activeStatus]?.items[activeStatusIdx]?.likes} Like</span><span style={{fontSize:14}}>💬 {statusList[activeStatus]?.items[activeStatusIdx]?.comments.length} Reply</span><span style={{fontSize:14}}>👁️ {statusList[activeStatus]?.items[activeStatusIdx]?.views} Views</span></div><div style={{display:"flex",gap:6,overflowX:"auto"}}><button onClick={()=>shareStatusTo(activeStatus,activeStatusIdx,"timeline")} style={{padding:"8px 12px",borderRadius:20,background:"#2563eb",color:"white",border:"none",fontSize:11,whiteSpace:"nowrap"}}>↗️ Share to Timeline</button><button onClick={()=>shareStatusTo(activeStatus,activeStatusIdx,"whatsapp")} style={{padding:"8px 12px",borderRadius:20,background:"#25D366",color:"white",border:"none",fontSize:11,whiteSpace:"nowrap"}}>💬 Share to WhatsApp (register gate)</button>{hostels.slice(0,3).map(h=><button key={h} onClick={()=>shareStatusTo(activeStatus,activeStatusIdx,h)} style={{padding:"8px 12px",borderRadius:20,background:"white",color:"black",border:"none",fontSize:11,whiteSpace:"nowrap"}}>🏠 {h}</button>)}</div><div style={{marginTop:12,display:"flex",gap:8}}><input placeholder="Reply to status..." style={{flex:1,padding:10,borderRadius:20,border:"none"}}/><button style={{background:"#2563eb",color:"white",border:"none",padding:"10px 16px",borderRadius:20}}>Send</button></div></div>{statusList[activeStatus]?.items.length>1&&<div style={{display:"flex",gap:4,padding:8}}>{statusList[activeStatus]?.items.map((_,ii)=><div key={ii} onClick={()=>setActiveStatusIdx(ii)} style={{flex:1,height:3,background:ii===activeStatusIdx?"white":"rgba(255,255,255,0.3)",borderRadius:2}}></div>)}</div>}</div>}

{tab==="feed"&&<div style={{padding:12}}><div style={{background:"white",padding:12,borderRadius:16,marginBottom:12}}><textarea value={txt} onChange={e=>setTxt(e.target.value)} placeholder={`What's happening in ${myHostel}?`} style={{width:"100%",background:"#f3f4f6",border:"none",padding:12,borderRadius:12,outline:"none"}} rows={2}/><button onClick={()=>{if(txt.trim()){setPosts([{id:Date.now(),name:"You",tag:myHostel,time:"now",text:txt,reaction:"❤️",reactionsCount:0,liked:false,cat:"general",verified:true,comments:[]},...posts]); setTxt("")}}} style={{marginTop:8,width:"100%",background:"#2563eb",color:"white",padding:10,borderRadius:10,border:"none",fontWeight:"bold"}}>Post to {myHostel} + Share to WhatsApp 🔐</button></div>
{posts.map(p=><div key={p.id} style={{background:"white",padding:14,borderRadius:14,marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between"}}><div style={{display:"flex",gap:8}}><div style={{width:36,height:36,background:"#e5e7eb",borderRadius:18}}></div><div><div style={{fontWeight:"bold",fontSize:13}}>{p.name} ✓</div><div style={{fontSize:11,color:"#6b7280"}}>{p.tag} • {p.time}</div></div></div><button onClick={()=>shareToWhatsapp(p.text,false)} style={{background:"#25D366",color:"white",border:"none",padding:"6px 10px",borderRadius:20,fontSize:10}}>💬 WhatsApp + Register Gate</button></div><div style={{marginTop:10}}>{p.text}</div><div style={{marginTop:10,display:"flex",gap:14,alignItems:"center",borderTop:"1px solid #f3f4f6",paddingTop:10,position:"relative"}}><span onClick={()=>setShowReactions(showReactions===p.id?null:p.id)} style={{fontWeight:"bold",fontSize:12}}>{p.reaction} {p.reactionsCount} • 30 Reactions</span><span onClick={()=>setCommentFor(commentFor===p.id?null:p.id)} style={{fontWeight:"bold",fontSize:12}}>💬 Comment ({p.comments.length})</span><span onClick={()=>setShareFor(shareFor===p.id?null:p.id)} style={{fontWeight:"bold",fontSize:12}}>↗️ Share</span></div>
{showReactions===p.id&&<div style={{marginTop:8,background:"white",border:"1px solid #eee",borderRadius:12,padding:8,display:"flex",gap:6,flexWrap:"wrap",boxShadow:"0 4px 12px rgba(0,0,0,0.1)"}}>{reactions30.map(r=><span key={r} onClick={()=>reactPost(p.id,r)} style={{fontSize:20,padding:4}}>{r}</span>)}</div>}
{commentFor===p.id&&<div style={{marginTop:10}}>{p.comments.map(c=><div key={c.id} style={{background:"#f3f4f6",padding:10,borderRadius:12,marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between"}}><div><b style={{fontSize:12}}>{c.name} {c.reaction}</b><div style={{fontSize:13}}>{c.text}</div>{c.voice&&<audio controls src={c.voice} style={{width:150,marginTop:6}}/>}</div><span style={{fontSize:11}}>{c.reaction} {c.reactionsCount}</span></div><div style={{display:"flex",gap:10,marginTop:6,flexWrap:"wrap"}}><span onClick={()=>{setReplyFor(c.id); setCommentTxt(`@${c.name} `)}} style={{fontSize:11,color:"#2563eb"}}>Reply</span><span onClick={()=>setShowReactions(showReactions===`c-${c.id}`?null:`c-${c.id}`)} style={{fontSize:11,color:"#2563eb"}}>React (30)</span><span onClick={()=>shareToWhatsapp(c.text,true)} style={{fontSize:11,color:"#25D366"}}>💬 WhatsApp</span>{c.name==="You"&&<><span onClick={()=>startEditComment(c)} style={{fontSize:11,color:"#6b7280"}}>✏️ Edit</span><span onClick={()=>deleteComment(p.id,c.id)} style={{fontSize:11,color:"red"}}>🗑️ Delete</span></>}</div>{showReactions===`c-${c.id}`&&<div style={{marginTop:6,display:"flex",gap:4,flexWrap:"wrap"}}>{reactions30.slice(0,10).map(r=><span key={r} onClick={()=>reactComment(p.id,c.id,r)} style={{fontSize:16}}>{r}</span>)}</div>)}
<div style={{marginTop:8,background:"white",border:"1px solid #e5e7eb",borderRadius:20,padding:"6px 10px",display:"flex",gap:6,alignItems:"center"}}><button onClick={()=>setShowMentions(!showMentions)} style={{border:"none",background:"#f3f4f6",borderRadius:15,padding:"5px 8px"}}>@</button><button onClick={()=>setShowStickers(!showStickers)} style={{border:"none",background:"#f3f4f6",borderRadius:15,padding:"5px 8px"}}>😊</button><button onClick={()=>isRecording?stopRecording():startRecording("comment")} style={{border:"none",background:isRecording?"red":"#f3f4f6",color:isRecording?"white":"black",borderRadius:15,padding:"5px 8px",fontSize:11}}>{isRecording&&recordingFor==="comment"?"⏹️ 1min":"🎤"}</button><input value={commentTxt} onChange={e=>setCommentTxt(e.target.value)} placeholder={editComment?"Edit comment...":"Comment... 1min voice max"} style={{flex:1,border:"none",outline:"none",fontSize:12}}/><button onClick={()=>addComment(p)} style={{background:"#2563eb",color:"white",border:"none",padding:"6px 12px",borderRadius:15,fontSize:11,fontWeight:"bold"}}>{editComment?"Save":"Post"}</button></div></div></div>)}</div>}

{tab==="community"&&<div style={{padding:12}}><h2>🏠 Hostels - Join/Leave + Member Count</h2><div style={{marginTop:12,display:"flex",flexDirection:"column",gap:8}}>{hostels.map(h=><div key={h} style={{background:"white",padding:14,borderRadius:12,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:"bold",fontSize:13}}>🏠 {h}</div><div style={{fontSize:11,color:"#6b7280"}}>👥 {hostelMembers[h]||100} members • {joinedHostels.includes(h)?"Joined ✓":"Not joined"}</div></div><button onClick={()=>toggleHostel(h)} style={{padding:"8px 14px",borderRadius:20,border:"none",background:joinedHostels.includes(h)?"#fee2e2": "#dcfce7",color:joinedHostels.includes(h)?"#dc2626":"#16a34a",fontWeight:"bold",fontSize:11}}>{joinedHostels.includes(h)?"Leave":"Join"}</button></div>)}</div></div>}

{tab==="market"&&<div style={{padding:12}}><h2>🛒 Marketplace + Price Filter + Delete Sold</h2><div style={{background:"white",padding:10,borderRadius:12,marginTop:10,display:"flex",gap:6}}><button onClick={()=>setPriceFilter("all")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:priceFilter==="all"?"#2563eb":"#f3f4f6",color:priceFilter==="all"?"white":"black",fontSize:11}}>All</button><button onClick={()=>setPriceFilter("low")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:priceFilter==="low"?"#2563eb":"#f3f4f6",color:priceFilter==="low"?"white":"black",fontSize:11}}>Under ₦2k</button><button onClick={()=>setPriceFilter("mid")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:priceFilter==="mid"?"#2563eb":"#f3f4f6",color:priceFilter==="mid"?"white":"black",fontSize:11}}>₦2k-10k</button><button onClick={()=>setPriceFilter("high")} style={{padding:"6px 10px",borderRadius:20,border:"none",background:priceFilter==="high"?"#2563eb":"#f3f4f6",color:priceFilter==="high"?"white":"black",fontSize:11}}>Above ₦10k</button></div><div style={{marginTop:10,display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>{filteredMarket.map(m=><div key={m.id} style={{background:m.sold?"#fee2e2":"white",padding:10,borderRadius:12,opacity:m.sold?0.6:1}}><div>{m.img} {m.name}</div><div style={{fontWeight:"bold"}}>{m.priceText} {m.sold&&" - SOLD"}</div><div style={{fontSize:11,color:"#6b7280"}}>{m.hostel} • {m.seller}</div>{m.seller==="You"&&<div style={{display:"flex",gap:6,marginTop:6}}><button onClick={()=>markSold(m.id)} style={{flex:1,padding:6,borderRadius:8,border:"none",background:"#f59e0b",color:"white",fontSize:10}}>{m.sold?"Sold":"Mark Sold"}</button><button onClick={()=>deleteMarketItem(m.id)} style={{flex:1,padding:6,borderRadius:8,border:"none",background:"#ef4444",color:"white",fontSize:10}}>🗑️ Delete</button></div>}</div>)}</div></div>}

{tab==="chat"&&<div style={{display:"flex",flexDirection:"column",height:"85vh"}}><div style={{background:"white",padding:12,borderBottom:"1px solid #eee",display:"flex",justifyContent:"space-between"}}><span onClick={()=>setTab("feed")}>← Feed</span><b>💬 Chat - Voice, Video, Image</b><span style={{fontSize:10,background:"#dcfce7",padding:"4px 8px",borderRadius:10}}>Voice Long + 1min comment</span></div><div style={{flex:1,padding:12,overflowY:"auto",display:"flex",flexDirection:"column",gap:8}}>{messages.map(m=><div key={m.id} style={{alignSelf:m.from==="you"?"flex-end":"flex-start",background:m.from==="you"?"#2563eb":"white",color:m.from==="you"?"white":"black",padding:10,borderRadius:14,maxWidth:"75%"}}>{m.type==="voice"?<><div style={{display:"flex",alignItems:"center",gap:8}}><span>🎤</span><audio controls src={m.url} style={{width:150}}/><span style={{fontSize:10}}>{m.duration}</span></div></>:m.type==="image"?<><img src={m.url} style={{width:150,borderRadius:8}}/><div style={{fontSize:11,marginTop:4}}>{m.text}</div></>:<div>{m.text}</div>}</div>)}</div><div style={{background:"white",padding:10,display:"flex",gap:6,alignItems:"center"}}><label style={{background:"#f3f4f6",padding:10,borderRadius:20}}>📷<input type="file" accept="image/*" onChange={e=>{const f=e.target.files[0]; if(f){const r=new FileReader(); r.onload=(ev)=>{setMessages([...messages,{id:Date.now(),from:"you",text:"📷 Image",type:"image",url:ev.target.result,item:activeChat?.name}])}; r.readAsDataURL(f)}}} style={{display:"none"}}/></label><label style={{background:"#f3f4f6",padding:10,borderRadius:20}}>🎥<input type="file" accept="video/*" onChange={e=>{const f=e.target.files[0]; if(f){const url=URL.createObjectURL(f); setMessages([...messages,{id:Date.now(),from:"you",text:"🎥 Video note",type:"video",url,item:activeChat?.name}])}}} style={{display:"none"}}/></label><button onClick={()=>isRecording?stopRecording():startRecording("chat")} style={{background:isRecording?"red":"#f3f4f6",border:"none",padding:10,borderRadius:20}}>{isRecording&&recordingFor==="chat"?"⏹️ Stop (long)":"🎤 Voice (long)"}</button><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Message + @mention..." style={{flex:1,padding:10,borderRadius:20,border:"1px solid #eee"}}/><button onClick={()=>{if(!chatInput.trim()) return; setMessages([...messages,{id:Date.now(),from:"you",text:chatInput,type:"text",item:activeChat?.name}]); setChatInput(""); setTimeout(()=>{setMessages(v=>[...v,{id:Date.now()+1,from:"seller",text:"Ok boss 👍",type:"text",item:activeChat?.name}]); pushNotif("New message 💬","message"); setUnreadMsgs(u=>u+1); playTone("message")},1000)}} style={{background:"#2563eb",color:"white",border:"none",padding:10,borderRadius:20}}>Send</button></div></div>}

{tab==="notifs"&&<div style={{padding:12}}><h2>🔔 Push Notifications (even when closed) 🔊</h2><div style={{fontSize:11,color:"#6b7280",marginTop:4}}>Browser push enabled - you get notification even when app closed</div><div style={{marginTop:12,display:"flex",flexDirection:"column",gap:8}}>{notifications.map(n=><div key={n.id} style={{background:"white",padding:12,borderRadius:12}}><b style={{fontSize:12}}>{n.text}</b><div style={{fontSize:10,color:"#6b7280"}}>{n.time} • Push + Tone 🔊 • Works closed</div></div>)}</div></div>}

<div style={{position:"fixed",bottom:0,left:0,right:0,background:"white",borderTop:"1px solid #eee",display:"flex",justifyContent:"space-around",padding:"10px 0",fontSize:10,fontWeight:"bold"}}><span onClick={()=>setTab("feed")} style={{color:tab==="feed"?"#2563eb":"#9ca3af"}}>📱 Feed</span><span onClick={()=>setTab("status")} style={{color:tab==="status"?"#2563eb":"#9ca3af"}}>📸 Status {statusList.reduce((a,b)=>a+b.items.length,0)}</span><span onClick={()=>setTab("community")} style={{color:tab==="community"?"#2563eb":"#9ca3af"}}>🏠 Hostels ({joinedHostels.length})</span><span onClick={()=>setTab("market")} style={{color:tab==="market"?"#2563eb":"#9ca3af"}}>🛒 Market</span><span onClick={()=>setTab("chat")} style={{color:tab==="chat"?"#2563eb":"#9ca3af"}}>💬 Chat</span></div>
</div>
)}
